repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.26
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.14'  # or any later Vulture version
    hooks:
      - id: vulture
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest -v --cov=src --cov-report term-missing
        language: python
        pass_filenames: false
        always_run: true
      - id: repo-map
        name: repo_map
        entry: uv
        language: system
        pass_filenames: false
        args:
          - run
          - -m
          - repo_mapper
          - --repo-root
          - .
          - --readme-path
          - ./README.md
          - --gitignore-path
          - ./.gitignore
          - --allowed-exts
          - py,md,yaml,toml,lock
          - --ignore-dirs
          - .venv,docs,.git,configs,mock_data
